// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

public class FlashScoreTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    protected void TearDown()
    {
        driver.Quit();
    }

    public void flashScore()
    {
        driver.Navigate().GoToUrl("https://www.flashscore.pl/");
        driver.Manage().Window.Size = new System.Drawing.Size(1235, 688);
        driver.FindElement(By.LinkText("Premier League")).Click();
        driver.FindElement(By.Id("li1")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".menuTop__item > .sportIcon--hockey"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".menuTop__item:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
    }
}